import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  isSpanish: boolean;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  // Navigation
  'nav.home': { es: 'Inicio', en: 'Home' },
  'nav.about': { es: 'Acerca de', en: 'About' },
  'nav.newcomers': { es: 'Soy Nuevo', en: 'Connect' },
  'nav.prayer': { es: 'Oración', en: 'Prayer' },
  'nav.live': { es: 'En Vivo', en: 'Live' },
  'nav.services': { es: 'Servicios', en: 'Services' },
  'nav.ministries': { es: 'Ministerios', en: 'Ministries' },
  'nav.events': { es: 'Eventos', en: 'Events' },
  'nav.contact': { es: 'Contacto', en: 'Contact' },
  'nav.giving': { es: 'Diezmos y Ofrendas', en: 'Giving' },
  
  // Hero Section
  'hero.title': { es: 'I.C.G.G.', en: 'I.C.G.G.' },
  'hero.subtitle': { es: 'Iglesia Cristiana Gracia y Gloria', en: 'Grace and Glory Christian Church' },
  'hero.welcome': { es: 'Bienvenidos a nuestra familia de fe', en: 'Welcome to our family of faith' },
  'hero.welcomeEn': { es: 'Welcome to our family of faith', en: 'Bienvenidos a nuestra familia de fe' },
  'hero.joinUs': { es: 'Únete a Nosotros', en: 'Join Us' },
  'hero.viewServices': { es: 'Nuestros Servicios', en: 'View Services' },
  
  // About Section
  'about.title': { es: 'Acerca de Nosotros', en: 'About Us' },
  'about.description': { es: 'Somos una comunidad de fe comprometida con compartir el amor de Cristo y servir a nuestra comunidad en Sanford, Florida.', en: 'We are a faith community committed to sharing the love of Christ and serving our community in Sanford, Florida.' },
  'about.beliefs': { es: 'Lo que Creemos', en: 'What We Believe' },
  'about.mission': { es: 'Nuestra Misión', en: 'Our Mission' },
  'about.missionText1': { es: 'En I.C.G.G., creemos en el poder transformador del evangelio de Jesucristo. Nuestra misión es crear un ambiente donde las familias puedan crecer espiritualmente, encontrar comunidad auténtica y servir a otros con amor.', en: 'At I.C.G.G., we believe in the transforming power of the gospel of Jesus Christ. Our mission is to create an environment where families can grow spiritually, find authentic community, and serve others with love.' },
  'about.missionText2': { es: 'Nos dedicamos a predicar la Palabra de Dios con fidelidad, discipular a los creyentes en su fe, y alcanzar nuestra comunidad con el mensaje de esperanza y salvación.', en: 'We are dedicated to preaching God\'s Word faithfully, discipling believers in their faith, and reaching our community with the message of hope and salvation.' },
  'about.love': { es: 'Amor', en: 'Love' },
  'about.loveDesc': { es: 'Amamos a Dios y a nuestro prójimo', en: 'We love God and our neighbor' },
  'about.community': { es: 'Comunidad', en: 'Community' },
  'about.communityDesc': { es: 'Construimos relaciones auténticas', en: 'We build authentic relationships' },
  'about.word': { es: 'Palabra', en: 'Word' },
  'about.wordDesc': { es: 'Enseñamos la Biblia con fidelidad', en: 'We teach the Bible faithfully' },
  'about.faith': { es: 'Fe', en: 'Faith' },
  'about.faithDesc': { es: 'Vivimos por fe en Cristo Jesús', en: 'We live by faith in Christ Jesus' },

  // Beliefs Modal
  'beliefs.title': { es: 'QUE CREEMOS', en: 'WHAT WE BELIEVE' },
  'beliefs.intro': { es: 'En Reacción En Cadena Ministries & Iglesia Cristiana Gracia y Gloria, creemos en el mensaje transformador del Evangelio de Jesucristo y en el poder de Dios para cambiar vidas hoy.', en: 'At Reacción En Cadena Ministries & Grace and Glory Christian Church, we believe in the transforming message of the Gospel of Jesus Christ and in the power of God to change lives today.' },
  'beliefs.webelieve': { es: 'Creemos que:', en: 'We believe that:' },
  'beliefs.belief1.title': { es: '1. La Biblia es la Palabra de Dios', en: '1. The Bible is the Word of God' },
  'beliefs.belief1.text': { es: 'Es inspirada por Dios, verdadera y la autoridad final para nuestra fe y nuestra vida.', en: 'It is inspired by God, true, and the final authority for our faith and our life.' },
  'beliefs.belief1.verse': { es: '(2 Timoteo 3:16)', en: '(2 Timothy 3:16)' },
  'beliefs.belief2.title': { es: '2. Hay un solo Dios', en: '2. There is One God' },
  'beliefs.belief2.text': { es: 'Dios se ha revelado como Padre, Hijo y Espíritu Santo.', en: 'God has revealed Himself as Father, Son, and Holy Spirit.' },
  'beliefs.belief2.verse': { es: '(Mateo 28:19)', en: '(Matthew 28:19)' },
  'beliefs.belief3.title': { es: '3. Jesucristo es el Hijo de Dios y el Salvador del mundo', en: '3. Jesus Christ is the Son of God and the Savior of the World' },
  'beliefs.belief3.text': { es: 'Creemos que Jesús murió en la cruz por nuestros pecados, resucitó al tercer día y hoy vive y reina.', en: 'We believe that Jesus died on the cross for our sins, rose on the third day, and today lives and reigns.' },
  'beliefs.belief3.verse': { es: '(Juan 3:16 / Romanos 10:9)', en: '(John 3:16 / Romans 10:9)' },
  'beliefs.belief4.title': { es: '4. La salvación es por gracia', en: '4. Salvation is by Grace' },
  'beliefs.belief4.text': { es: 'Nadie puede salvarse por sus obras. Somos salvos por la gracia de Dios mediante la fe en Jesucristo.', en: 'No one can be saved by their works. We are saved by the grace of God through faith in Jesus Christ.' },
  'beliefs.belief4.verse': { es: '(Efesios 2:8-9)', en: '(Ephesians 2:8-9)' },
  'beliefs.belief5.title': { es: '5. El Espíritu Santo obra hoy', en: '5. The Holy Spirit Works Today' },
  'beliefs.belief5.text': { es: 'El Espíritu Santo transforma vidas, guía al creyente y capacita a la Iglesia para cumplir la misión de Dios en el mundo.', en: 'The Holy Spirit transforms lives, guides the believer, and empowers the Church to fulfill God\'s mission in the world.' },
  'beliefs.belief5.verse': { es: '(Hechos 1:8)', en: '(Acts 1:8)' },
  'beliefs.belief6.title': { es: '6. La Iglesia es el cuerpo de Cristo', en: '6. The Church is the Body of Christ' },
  'beliefs.belief6.text': { es: 'Somos llamados a vivir en comunidad, crecer como discípulos y llevar el mensaje de esperanza al mundo.', en: 'We are called to live in community, grow as disciples, and bring the message of hope to the world.' },
  'beliefs.belief7.title': { es: '7. Jesucristo volverá', en: '7. Jesus Christ Will Return' },
  'beliefs.belief7.text': { es: 'Creemos en la segunda venida de Cristo y en el establecimiento pleno de su Reino.', en: 'We believe in the second coming of Christ and in the full establishment of His Kingdom.' },
  'beliefs.bornagain.title': { es: 'CÓMO NACER DE NUEVO', en: 'HOW TO BE BORN AGAIN' },
  'beliefs.bornagain.question': { es: '¿Cómo puedes ser salvo?', en: 'How can you be saved?' },
  'beliefs.bornagain.intro': { es: 'La Biblia enseña que todos necesitamos una nueva vida en Dios.', en: 'The Bible teaches that we all need a new life in God.' },
  'beliefs.bornagain.jesussaid': { es: 'Jesús dijo: "El que no naciere de nuevo, no puede ver el reino de Dios."', en: 'Jesus said: "Unless one is born again, he cannot see the kingdom of God."' },
  'beliefs.bornagain.verse': { es: '(Juan 3:3)', en: '(John 3:3)' },
  'beliefs.bornagain.meaning': { es: 'Nacer de nuevo significa comenzar una relación real con Dios por medio de Jesucristo.', en: 'Being born again means beginning a real relationship with God through Jesus Christ.' },
  'beliefs.bornagain.steps': { es: 'Tres pasos bíblicos', en: 'Three Biblical Steps' },
  'beliefs.bornagain.step1.title': { es: 'Reconocer que necesitas a Dios', en: 'Recognize that you need God' },
  'beliefs.bornagain.step1.text': { es: 'Todos hemos pecado y estamos separados de Dios.', en: 'We have all sinned and are separated from God.' },
  'beliefs.bornagain.step1.verse': { es: '(Romanos 3:23)', en: '(Romans 3:23)' },
  'beliefs.bornagain.step2.title': { es: 'Creer en Jesucristo', en: 'Believe in Jesus Christ' },
  'beliefs.bornagain.step2.text': { es: 'Jesús murió en la cruz para perdonar nuestros pecados y reconciliarnos con Dios.', en: 'Jesus died on the cross to forgive our sins and reconcile us with God.' },
  'beliefs.bornagain.step2.verse': { es: '(Romanos 5:8)', en: '(Romans 5:8)' },
  'beliefs.bornagain.step3.title': { es: 'Recibir a Cristo en tu vida', en: 'Receive Christ in your life' },
  'beliefs.bornagain.step3.text': { es: 'Cuando abres tu corazón a Jesús y lo confiesas como Señor, recibes una nueva vida.', en: 'When you open your heart to Jesus and confess Him as Lord, you receive a new life.' },
  'beliefs.bornagain.step3.verse': { es: '(Romanos 10:9-10)', en: '(Romans 10:9-10)' },
  'beliefs.bornagain.prayer.title': { es: 'Una oración sencilla', en: 'A Simple Prayer' },
  'beliefs.bornagain.prayer.intro': { es: 'Puedes comenzar tu relación con Dios con una oración como esta:', en: 'You can begin your relationship with God with a prayer like this:' },
  'beliefs.bornagain.prayer.text': { es: '"Señor Jesús, reconozco que te necesito.\nCreo que moriste por mis pecados y resucitaste.\nHoy te recibo como mi Señor y Salvador.\nPerdona mis pecados y hazme una nueva persona.\nDesde hoy decido seguirte. Amén."', en: '"Lord Jesus, I recognize that I need You.\nI believe that You died for my sins and rose again.\nToday I receive You as my Lord and Savior.\nForgive my sins and make me a new person.\nFrom today I decide to follow You. Amen."' },
  'beliefs.bornagain.prayer.conclusion': { es: 'Si hiciste esta oración con fe, has comenzado una nueva vida con Dios.', en: 'If you made this prayer with faith, you have begun a new life with God.' },
  'beliefs.nextsteps.title': { es: 'PRÓXIMOS PASOS', en: 'NEXT STEPS' },
  'beliefs.nextsteps.intro': { es: 'La vida cristiana es un camino de crecimiento. Estos son los primeros pasos para crecer en tu fe:', en: 'The Christian life is a path of growth. These are the first steps to grow in your faith:' },
  'beliefs.nextsteps.step1.title': { es: '1. Conéctate con la iglesia', en: '1. Connect with the church' },
  'beliefs.nextsteps.step1.text': { es: 'La fe se fortalece cuando caminamos en comunidad.', en: 'Faith is strengthened when we walk in community.' },
  'beliefs.nextsteps.step2.title': { es: '2. Bautízate en agua', en: '2. Get baptized in water' },
  'beliefs.nextsteps.step2.text': { es: 'El bautismo es una declaración pública de tu nueva vida en Cristo.', en: 'Baptism is a public declaration of your new life in Christ.' },
  'beliefs.nextsteps.step2.verse': { es: '(Mateo 28:19)', en: '(Matthew 28:19)' },
  'beliefs.nextsteps.step3.title': { es: '3. Crece como discípulo', en: '3. Grow as a disciple' },
  'beliefs.nextsteps.step3.text': { es: 'Participa en nuestras clases y grupos de formación para crecer en la Palabra de Dios.', en: 'Participate in our classes and formation groups to grow in the Word of God.' },
  'beliefs.nextsteps.step4.title': { es: '4. Descubre tu propósito', en: '4. Discover your purpose' },
  'beliefs.nextsteps.step4.text': { es: 'Dios ha puesto dones y un llamado en tu vida.', en: 'God has placed gifts and a calling in your life.' },
  'beliefs.nextsteps.step5.title': { es: '5. Vive la misión', en: '5. Live the mission' },
  'beliefs.nextsteps.step5.text': { es: 'Todos somos llamados a compartir el amor de Jesús y servir a otros.', en: 'We are all called to share the love of Jesus and serve others.' },
  'beliefs.nextsteps.prayer': { es: 'Nuestra oración es que experimentes el amor de Dios, descubras tu propósito y vivas una vida que impacte a otros para Cristo.', en: 'Our prayer is that you experience God\'s love, discover your purpose, and live a life that impacts others for Christ.' },
  'beliefs.nextsteps.signature': { es: 'Ps Irene Familia', en: 'Ps Irene Familia' },
  'beliefs.close': { es: 'Cerrar', en: 'Close' },

  // Live Stream Section
  'live.title': { es: 'Transmisión En Vivo', en: 'Live Stream' },
  'live.description': { es: 'Únete a nosotros en línea para nuestros servicios en vivo', en: 'Join us online for our live services' },
  'live.serviceTitle': { es: 'Servicio En Vivo', en: 'Live Service' },
  'live.followFacebook': { es: 'Síguenos en Facebook', en: 'Follow us on Facebook' },
  'live.followDescription': { es: 'Aquí puedes ver nuestras últimas publicaciones, fotos de eventos y anuncios importantes', en: 'Here you can see our latest posts, event photos and important announcements' },
  'live.cantSee': { es: '¿No puedes ver las publicaciones? Visita nuestra página directamente', en: 'Can\'t see the posts? Visit our page directly' },
  'live.viewFacebook': { es: 'Ver en Facebook', en: 'View on Facebook' },
  'live.announcements': { es: 'Anuncios', en: 'Announcements' },
  'live.announcementsDesc': { es: 'Recibe notificaciones sobre eventos especiales y actividades', en: 'Receive notifications about special events and activities' },
  'live.events': { es: 'Eventos', en: 'Events' },
  'live.eventsDesc': { es: 'Mantente informado sobre próximos eventos y actividades', en: 'Stay informed about upcoming events and activities' },
  'live.photos': { es: 'Fotos', en: 'Photos' },
  'live.photosDesc': { es: 'Ve fotos de nuestros servicios y eventos especiales', en: 'View photos from our services and special events' },
  'live.cantAttend': { es: '¿No puedes asistir en persona?', en: 'Can\'t attend in person?' },
  'live.cantAttendDesc': { es: '¡No te preocupes! Puedes unirte a nosotros en línea durante nuestros servicios en vivo', en: 'Don\'t worry! You can join us online during our live services' },
  'live.scheduleInfo': { es: 'Nuestras transmisiones en vivo están disponibles todos los domingos a las 10:00 AM y jueves a las 7:30 PM.', en: 'Our live streams are available every Sunday at 10:00 AM and Thursday at 7:30 PM.' },
  'live.experienceInfo': { es: 'Experimenta la adoración y la enseñanza desde la comodidad de tu hogar.', en: 'Experience worship and teaching from the comfort of your home.' },
  'live.sunday': { es: 'Domingo', en: 'Sunday' },
  'live.thursday': { es: 'Jueves', en: 'Thursday' },
  'live.mainService': { es: 'Servicio Principal', en: 'Main Service' },
  'live.bibleStudy': { es: 'Estudio Bíblico', en: 'Bible Study' },
  'live.prayerPraise': { es: 'Oración y Alabanza', en: 'Prayer and Praise' },
  'live.liveLabel': { es: 'EN VIVO', en: 'LIVE' },
  
  // Services Section
  'services.title': { es: 'Horarios de Servicios', en: 'Service Times' },
  'services.description': { es: 'Te invitamos a acompañarnos en nuestros servicios de adoración y enseñanza', en: 'We invite you to join us for our worship and teaching services' },
  'services.sunday': { es: 'Domingo', en: 'Sunday' },
  'services.thursday': { es: 'Jueves', en: 'Thursday' },
  'services.friday': { es: 'Viernes', en: 'Friday' },
  'services.mainService': { es: 'Servicio Principal', en: 'Main Service' },
  'services.bibleStudy': { es: 'Estudio Bíblico', en: 'Bible Study' },
  'services.prayerPraise': { es: 'Oración y Alabanza', en: 'Prayer and Praise' },
  'services.youthService': { es: 'Servicio de Jóvenes', en: 'Youth Service' },
  'services.worshipWord': { es: 'Adoración y Palabra', en: 'Worship and Word' },
  'services.location': { es: 'Nuestra Ubicación', en: 'Our Location' },
  'services.locationDesc': { es: '¡Ven y únete a nuestra familia de fe! Todos son bienvenidos.', en: 'Come and join our family of faith! Everyone is welcome.' },
  
  // Ministries Section
  'ministries.title': { es: 'Nuestros Ministerios', en: 'Our Ministries' },
  'ministries.description': { es: 'Ofrecemos diversos ministerios para servir a toda la familia y la comunidad', en: 'We offer various ministries to serve the entire family and community' },
  'ministries.adults': { es: 'Ministerio de Adultos', en: 'Adult Ministry' },
  'ministries.adultsDesc': { es: 'Grupos de estudio bíblico y compañerismo para adultos de todas las edades', en: 'Bible study groups and fellowship for adults of all ages' },
  'ministries.children': { es: 'Ministerio Infantil', en: 'Children\'s Ministry' },
  'ministries.childrenDesc': { es: 'Educación cristiana y actividades para niños de 0-12 años', en: 'Christian education and activities for children ages 0-12' },
  'ministries.worship': { es: 'Ministerio de Alabanza', en: 'Worship Ministry' },
  'ministries.worshipDesc': { es: 'Coro, músicos y equipo de sonido para la adoración congregacional', en: 'Choir, musicians and sound team for congregational worship' },
  'ministries.compassion': { es: 'Ministerio de Compasión', en: 'Compassion Ministry' },
  'ministries.compassionDesc': { es: 'Servicio a la comunidad, ayuda a necesitados y obras de misericordia', en: 'Community service, helping the needy and works of mercy' },
  'ministries.youth': { es: 'Ministerio de Jóvenes', en: 'Youth Ministry' },
  'ministries.youthDesc': { es: 'Actividades, estudios bíblicos y eventos especiales para adolescentes', en: 'Activities, Bible studies and special events for teenagers' },
  'ministries.family': { es: 'Grupos Familiares', en: 'Family Groups' },
  'ministries.familyDesc': { es: 'Reuniones en hogares para estudio bíblico y comunión íntima', en: 'Home meetings for Bible study and intimate fellowship' },
  'ministries.singles': { es: 'Ministerio de Solteros', en: 'Singles Ministry' },
  'ministries.singlesDesc': { es: 'Actividades, estudios bíblicos y compañerismo para jóvenes adultos solteros', en: 'Activities, Bible studies and fellowship for single young adults' },
  'ministries.marriage': { es: 'Ministerio de Matrimonios', en: 'Marriage Ministry' },
  'ministries.marriageDesc': { es: 'Fortalecimiento de matrimonios a través de estudios bíblicos y retiros', en: 'Strengthening marriages through Bible studies and retreats' },
  'ministries.men': { es: 'Ministerio de Caballeros', en: 'Men\'s Ministry' },
  'ministries.menDesc': { es: 'Reuniones de hombres para crecimiento espiritual y compañerismo cristiano', en: 'Men\'s meetings for spiritual growth and Christian fellowship' },
  'ministries.women': { es: 'Ministerio de Damas', en: 'Women\'s Ministry' },
  'ministries.womenDesc': { es: 'Estudios bíblicos y actividades especiales para mujeres de todas las edades', en: 'Bible studies and special activities for women of all ages' },
  'ministries.media': { es: 'Ministerio de Media', en: 'Media Ministry' },
  'ministries.mediaDesc': { es: 'Equipo de fotografía, video, sonido, redes sociales y tecnología para documentar y compartir la obra de Dios', en: 'Photography, video, sound, social media and technology team to document and share God\'s work' },
  'ministries.missions': { es: 'Ministerio de Misiones', en: 'Missions Ministry' },
  'ministries.missionsDesc': { es: 'Apoyo a misioneros locales e internacionales, viajes misioneros y evangelización global', en: 'Support for local and international missionaries, mission trips and global evangelization' },
  'ministries.evangelism': { es: 'Ministerio de Evangelismo', en: 'Evangelism Ministry' },
  'ministries.evangelismDesc': { es: 'Alcance comunitario, evangelización personal y eventos de testimonio para compartir el evangelio', en: 'Community outreach, personal evangelism and testimony events to share the gospel' },
  'ministries.pastor': { es: 'Nuestra Pastora', en: 'Our Pastor' },
  'ministries.pastorTitle': { es: 'Pastora Principal', en: 'Lead Pastor' },
  'ministries.pastorDesc': { es: 'Con años de experiencia en el ministerio pastoral, la Pastora Irene Familia ha dedicado su vida a servir a Dios y a su pueblo. Su corazón pastoral y su compromiso con la enseñanza bíblica han sido fundamentales en el crecimiento y desarrollo espiritual de nuestra congregación.', en: 'With years of experience in pastoral ministry, Pastor Irene Familia has dedicated her life to serving God and His people. Her pastoral heart and commitment to biblical teaching have been fundamental in the spiritual growth and development of our congregation.' },
  
  // Events Section
  'events.title': { es: '¡Acompañanos!', en: 'Upcoming Events' },
  'events.description': { es: 'Mantente conectado con todas nuestras actividades y eventos especiales', en: 'Stay connected with all our activities and special events' },
  'events.calendarTitle': { es: 'Horarios de Servicios', en: 'Service Schedule' },
  'events.calendarDescription': { es: 'Mantente informado sobre nuestros próximos eventos y actividades especiales', en: 'Stay informed about our upcoming events and special activities' },
  'events.stayInformed': { es: '¡Mantente Informado!', en: 'Stay Informed!' },
  'events.newsletter': { es: 'Suscríbete a nuestro boletín para recibir actualizaciones sobre eventos y actividades', en: 'Subscribe to our newsletter to receive updates about events and activities' },
  'events.emailPlaceholder': { es: 'Tu correo electrónico', en: 'Your email address' },
  'events.subscribe': { es: 'Suscribirse', en: 'Subscribe' },
  
  // Contact Section
  'contact.title': { es: 'Contáctanos', en: 'Contact Us' },
  'contact.description': { es: 'Estamos aquí para servirte. No dudes en contactarnos para cualquier pregunta o necesidad', en: 'We are here to serve you. Don\'t hesitate to contact us for any questions or needs' },
  'contact.info': { es: 'Información de Contacto', en: 'Contact Information' },
  'contact.address': { es: 'Dirección', en: 'Address' },
  'contact.email': { es: 'Correo Electrónico', en: 'Email' },
  'contact.officeHours': { es: 'Horarios de Oficina', en: 'Office Hours' },
  'contact.mondayFriday': { es: 'Lunes - Viernes: 9:00 AM - 5:00 PM', en: 'Monday - Friday: 9:00 AM - 5:00 PM' },
  'contact.saturday': { es: 'Sábado: 10:00 AM - 2:00 PM', en: 'Saturday: 10:00 AM - 2:00 PM' },
  'contact.sendMessage': { es: 'Envíanos un Mensaje', en: 'Send us a Message' },
  'contact.fullName': { es: 'Nombre Completo', en: 'Full Name' },
  'contact.fullNamePlaceholder': { es: 'Tu nombre completo', en: 'Your full name' },
  'contact.emailPlaceholder': { es: 'tu@email.com', en: 'your@email.com' },
  'contact.phone': { es: 'Teléfono', en: 'Phone' },
  'contact.subject': { es: 'Asunto', en: 'Subject' },
  'contact.selectSubject': { es: 'Selecciona un asunto', en: 'Select a subject' },
  'contact.prayer': { es: 'Petición de Oración', en: 'Prayer Request' },
  'contact.visit': { es: 'Quiero Visitar la Iglesia', en: 'I Want to Visit the Church' },
  'contact.ministryInfo': { es: 'Información sobre Ministerios', en: 'Ministry Information' },
  'contact.counseling': { es: 'Consejería Pastoral', en: 'Pastoral Counseling' },
  'contact.other': { es: 'Otro', en: 'Other' },
  'contact.message': { es: 'Mensaje', en: 'Message' },
  'contact.messagePlaceholder': { es: 'Comparte tu mensaje, petición de oración, o cualquier pregunta que tengas...', en: 'Share your message, prayer request, or any questions you have...' },
  'contact.sendButton': { es: 'Enviar Mensaje', en: 'Send Message' },
  'contact.directions': { es: 'Cómo Llegar', en: 'How to Get Here' },
  'contact.clickMaps': { es: 'Haz clic para abrir en Google Maps', en: 'Click to open in Google Maps' },
  
  // Giving Section
  'giving.title': { es: 'Diezmos y Ofrendas', en: 'Tithes and Offerings' },
  'giving.verse': { es: '"Cada uno dé como propuso en su corazón: no con tristeza, ni por necesidad, porque Dios ama al dador alegre." - 2 Corintios 9:7', en: '"Each one must give as he has decided in his heart, not reluctantly or under compulsion, for God loves a cheerful giver." - 2 Corinthians 9:7' },
  'giving.gratitude': { es: 'Dar con Gratitud', en: 'Give with Gratitude' },
  'giving.generosity': { es: 'Tu generosidad ayuda a expandir el Reino de Dios y bendecir a nuestra comunidad', en: 'Your generosity helps expand God\'s Kingdom and bless our community' },
  'giving.zelleDesc': { es: 'Envía tu diezmo u ofrenda directamente desde tu banco usando Zelle', en: 'Send your tithe or offering directly from your bank using Zelle' },
  'giving.zelleOfficial': { es: 'Ir a Zelle Oficial', en: 'Go to Official Zelle' },
  'giving.sendTo': { es: 'Enviar a:', en: 'Send to:' },
  'giving.instructions': { es: 'Instrucciones:', en: 'Instructions:' },
  'giving.step1': { es: '1. Abre tu app bancaria', en: '1. Open your banking app' },
  'giving.step2': { es: '2. Selecciona Zelle', en: '2. Select Zelle' },
  'giving.step3': { es: '3. Usa el email: Give@encadena.org', en: '3. Use email: Give@encadena.org' },
  'giving.step4': { es: '4. Ingresa el monto', en: '4. Enter the amount' },
  'giving.step5': { es: '5. En el memo escribe "Diezmo" u "Ofrenda"', en: '5. In memo write "Tithe" or "Offering"' },
  'giving.tithelyDesc': { es: 'Plataforma segura para dar con tarjeta de débito, crédito o cuenta bancaria', en: 'Secure platform to give with debit card, credit card or bank account' },
  'giving.giveNow': { es: 'Dar Ahora con Tithe.ly', en: 'Give Now with Tithe.ly' },
  'giving.paymentOptions': { es: 'Opciones de pago:', en: 'Payment options:' },
  'giving.debitCredit': { es: '• Tarjeta de débito/crédito', en: '• Debit/credit card' },
  'giving.bankTransfer': { es: '• Transferencia bancaria (ACH)', en: '• Bank transfer (ACH)' },
  'giving.oneTimeRecurring': { es: '• Dar una sola vez o recurrente', en: '• One-time or recurring giving' },
  'giving.secure': { es: '• 100% seguro y encriptado', en: '• 100% secure and encrypted' },
  'giving.whyGive': { es: '¿Por qué damos?', en: 'Why do we give?' },
  'giving.obedience': { es: 'Obediencia a Dios', en: 'Obedience to God' },
  'giving.obedienceDesc': { es: 'Damos porque Dios nos ha dado primero y es un acto de obediencia y adoración.', en: 'We give because God has given to us first and it is an act of obedience and worship.' },
  'giving.support': { es: 'Apoyo al Ministerio', en: 'Ministry Support' },
  'giving.supportDesc': { es: 'Nuestras ofrendas sostienen la obra del ministerio y las actividades de la iglesia.', en: 'Our offerings sustain the work of ministry and church activities.' },
  'giving.blessing': { es: 'Bendición a Otros', en: 'Blessing Others' },
  'giving.blessingDesc': { es: 'Ayudamos a los necesitados y apoyamos las misiones locales e internacionales.', en: 'We help those in need and support local and international missions.' },
  'giving.disclaimer': { es: 'Todas las donaciones son procesadas de forma segura. Para preguntas sobre donaciones, contacta a nuestra oficina.', en: 'All donations are processed securely. For questions about donations, contact our office.' },
  
  // Facebook Page Feed Section
  'facebook.title': { es: 'Síguenos en Facebook!', en: 'Follow us on Facebook!' },
  'facebook.description': { es: 'Mantente conectado con todas nuestras actividades y eventos especiales a través de Facebook', en: 'Stay connected with all our activities and special events through Facebook' },
 'facebook.followDescription': { es: 'Únete a nuestra comunidad en Facebook para ver fotos de nuestros servicios, recibir actualizaciones de eventos, y mantenerte conectado con la familia de I.C.G.G.', en: 'Join our Facebook community to see photos from our services, receive event updates, and stay connected with the I.C.G.G. family.' },
 'facebook.followButton': { es: 'Seguir en Facebook', en: 'Follow on Facebook' },
  
  // Events Section - Specific Events
  'events.prayer': { es: 'Oración', en: 'Prayer' },
  'events.everyWednesday': { es: 'Todos los Miércoles', en: 'Every Wednesday' },
  'events.prayerDesc': { es: 'Un tiempo dedicado a la oración comunitaria, intercesión y búsqueda de la presencia de Dios. Ven y únete a nosotros en Oración. Te Esperamos', en: 'A time dedicated to community prayer, intercession and seeking God\'s presence. Come and join us in Prayer. We are waiting for you' },
  'events.weekly': { es: 'Semanal', en: 'Weekly' },
  'events.artsSchool': { es: 'ICGG ARTS SANFORD SCHOOL', en: 'ICGG ARTS SANFORD SCHOOL' },
  'events.artsSept13': { es: 'Sábado, 13 de Septiembre', en: 'Saturday, Sept 13th' },
  'events.artsSchoolDesc': { es: 'Escuela de artes de ICGG en Sanford. Un programa especial para desarrollar talentos artísticos y creativos en un ambiente cristiano. Se reúne el segundo sábado de cada mes.', en: 'ICGG arts school in Sanford. A special program to develop artistic and creative talents in a Christian environment. Meets on the second Saturday of each month.' },
  'events.special': { es: 'Especial', en: 'Special' },
  'events.everyThursday': { es: 'Todos los Jueves', en: 'Every Thursday' },
  'events.everySunday': { es: 'Todos los Domingos', en: 'Every Sunday' },
  'events.celebration': { es: 'Celebración', en: 'Celebration' },
  'events.bibleStudyThursdays': { es: 'Estudio Bíblico todos los Jueves', en: 'Bible Study every Thursday' },
  'events.upsideDownSeries': { es: 'Serie Nueva - Upside Down - Pastora Irene Familia', en: 'New Series - Upside Down - Pastor Irene Familia' },
  'events.bibleStudyDesc': { es: 'Nueva serie de estudio bíblico "Upside Down" dirigida por la Pastora Irene Familia. Un tiempo de profundización en la Palabra de Dios.', en: 'New Bible study series "Upside Down" led by Pastor Irene Familia. A time of deepening in God\'s Word.' },
  'events.sundayService': { es: 'Servicio de Domingo', en: 'Sunday Service' },
  'events.sept14th': { es: '14 de Septiembre', en: 'Sept 14th' },
  'events.sundayServiceDesc': { es: 'Nuestro servicio principal de adoración dominical con predicación, alabanza y comunión.', en: 'Our main Sunday worship service with preaching, praise and communion.' },'events.allWelcome': { es: 'Todos bienvenidos', en: 'Everyone welcome' },
  
  // Alineados Section
  'alineados.title': { es: 'Una Nueva Herramienta para Parejas', en: 'A New Tool for Couples' },
  'alineados.subtitle': { es: 'Presentamos una aplicación diseñada para ayudar a las parejas a manejar sus finanzas juntos', en: 'Introducing an app designed to help couples manage their finances together' },
  'alineados.tagline': { es: 'Enfrentando Deudas Juntos', en: 'Tackling Debt Together' },
  'alineados.description': { es: 'Una aplicación innovadora creada para parejas que desean trabajar juntos para eliminar sus deudas y construir un futuro financiero sólido.', en: 'An innovative app created for couples who want to work together to eliminate their debt and build a solid financial future.' },
  'alineados.together': { es: 'Juntos', en: 'Together' },
  'alineados.togetherDesc': { es: 'Trabajen en equipo para alcanzar sus metas financieras', en: 'Work as a team to reach your financial goals' },
  'alineados.debts': { es: 'Deudas', en: 'Debts' },
  'alineados.debtsDesc': { es: 'Rastrear y eliminar deudas de manera efectiva', en: 'Track and eliminate debts effectively' },
  'alineados.transparency': { es: 'Transparencia', en: 'Transparency' },
  'alineados.transparencyDesc': { es: 'Comunicación abierta sobre finanzas', en: 'Open communication about finances' },
  'alineados.visit': { es: 'Visitar ALINEADOS', en: 'Visit ALINEADOS' },
  'alineados.features': { es: '💑 Para Parejas o Solteros • 💰 Gestión de Deudas • 🎯 Metas Financieras Compartidas', en: '💑 For Couples or Singles • 💰 Debt Management • 🎯 Shared Financial Goals' },

  // Aviva Kids Section
  'avivakids.title': { es: 'ICGG AVIVA KIDS', en: 'ICGG AVIVA KIDS' },
  'avivakids.subtitle': { es: 'Un lugar donde los niños descubren el amor de Jesús', en: 'A place where children discover the love of Jesus' },
  'avivakids.description': { es: 'Ministerio infantil diseñado para niños de 0 a 12 años con enseñanza bíblica, adoración divertida y actividades llenas de alegría', en: 'Children\'s ministry designed for kids ages 0-12 with biblical teaching, fun worship, and joy-filled activities' },
  'avivakids.nursery': { es: 'Cunas', en: 'Nursery' },
  'avivakids.nurseryAge': { es: '0-2 años', en: 'Ages 0-2' },
  'avivakids.nurseryDesc': { es: 'Cuidado amoroso en un ambiente seguro con canciones, juegos y tiempo de oración para los más pequeños.', en: 'Loving care in a safe environment with songs, games, and prayer time for the little ones.' },
  'avivakids.toddlers': { es: 'Párvulos', en: 'Toddlers' },
  'avivakids.toddlersAge': { es: '3-4 años', en: 'Ages 3-4' },
  'avivakids.toddlersDesc': { es: 'Historias bíblicas interactivas, alabanza con movimiento y actividades creativas adaptadas para preescolares.', en: 'Interactive Bible stories, worship with movement, and creative activities adapted for preschoolers.' },
  'avivakids.preschool': { es: 'Preescolar', en: 'Preschool' },
  'avivakids.preschoolAge': { es: '5-7 años', en: 'Ages 5-7' },
  'avivakids.preschoolDesc': { es: 'Lecciones bíblicas dinámicas, adoración energética, juegos y manualidades que refuerzan valores cristianos.', en: 'Dynamic Bible lessons, energetic worship, games, and crafts that reinforce Christian values.' },
  'avivakids.elementary': { es: 'Primaria', en: 'Elementary' },
  'avivakids.elementaryAge': { es: '8-12 años', en: 'Ages 8-12' },
  'avivakids.elementaryDesc': { es: 'Enseñanza profunda de la Palabra, tiempo de adoración, discusiones en grupo y proyectos prácticos de servicio.', en: 'Deep teaching of the Word, worship time, group discussions, and practical service projects.' },
  'avivakids.activitiesTitle': { es: '¿Qué Hacemos en Aviva Kids?', en: 'What Do We Do in Aviva Kids?' },
  'avivakids.biblestories': { es: 'Historias Bíblicas', en: 'Bible Stories' },
  'avivakids.biblestoriesDesc': { es: 'Enseñamos la Biblia de manera divertida y creativa para que los niños aprendan sobre Jesús y sus enseñanzas.', en: 'We teach the Bible in a fun and creative way so children learn about Jesus and His teachings.' },
  'avivakids.worship': { es: 'Alabanza y Adoración', en: 'Praise and Worship' },
  'avivakids.worshipDesc': { es: 'Canciones alegres y dinámicas que ayudan a los niños a conectarse con Dios a través de la música y el movimiento.', en: 'Joyful and dynamic songs that help children connect with God through music and movement.' },
  'avivakids.crafts': { es: 'Manualidades Creativas', en: 'Creative Crafts' },
  'avivakids.craftsDesc': { es: 'Proyectos artísticos y manualidades que refuerzan las lecciones bíblicas de manera práctica y memorable.', en: 'Art projects and crafts that reinforce Bible lessons in a practical and memorable way.' },
  'avivakids.games': { es: 'Juegos y Actividades', en: 'Games and Activities' },
  'avivakids.gamesDesc': { es: 'Juegos educativos que enseñan valores cristianos mientras los niños se divierten y hacen amigos.', en: 'Educational games that teach Christian values while children have fun and make friends.' },
  'avivakids.whenWhere': { es: '¿Cuándo y Dónde?', en: 'When & Where?' },
  'avivakids.sundayService': { es: 'Servicio Dominical', en: 'Sunday Service' },
  'avivakids.sundayTime': { es: 'Domingos a las 10:00 AM', en: 'Sundays at 10:00 AM' },
  'avivakids.location': { es: 'Ubicación', en: 'Location' },
  'avivakids.locationDetail': { es: 'Salones de niños en I.C.G.G.', en: 'Children\'s rooms at I.C.G.G.' },
  'avivakids.parentsTitle': { es: 'Información para Padres', en: 'Parent Information' },
  'avivakids.parentsInfo': { es: 'La seguridad de su hijo es nuestra prioridad. Todos nuestros maestros y voluntarios están certificados y capacitados. Tenemos protocolos de check-in/check-out para garantizar que su hijo esté seguro y bien cuidado durante todo el servicio.', en: 'Your child\'s safety is our priority. All our teachers and volunteers are certified and trained. We have check-in/check-out protocols to ensure your child is safe and well cared for throughout the service.' },
  'avivakids.visitWebsite': { es: 'Visita Aviva Kids', en: 'Visit Aviva Kids' },

  // Footer
  'footer.description': { es: 'Una iglesia comprometida con predicar el evangelio, discipular creyentes y servir a nuestra comunidad con el amor de Cristo. Todos son bienvenidos en nuestra familia de fe.', en: 'A church committed to preaching the gospel, discipling believers and serving our community with the love of Christ. Everyone is welcome in our family of faith.' },
  'footer.quickLinks': { es: 'Enlaces Rápidos', en: 'Quick Links' },
  'footer.contact': { es: 'Contacto', en: 'Contact' },
  'footer.serviceHours': { es: 'Horarios de Servicios', en: 'Service Hours' },
  'footer.sunday': { es: 'Domingo:', en: 'Sunday:' },
  'footer.thursday': { es: 'Jueves:', en: 'Thursday:' },
  'footer.friday': { es: 'Viernes:', en: 'Friday:' },
  'footer.copyright': { es: '© 2025 I.C.G.G. Iglesia Cristiana Gracia y Gloria. Todos los derechos reservados.', en: '© 2025 I.C.G.G. Grace and Glory Christian Church. All rights reserved.' },
  'footer.privacy': { es: 'Política de Privacidad', en: 'Privacy Policy' },
  'footer.terms': { es: 'Términos de Uso', en: 'Terms of Use' },
  'footer.designedBy': { es: 'Site designed by Finesse Media LLC', en: 'Site designed by Finesse Media LLC' },

  // Newcomers Section
  'newcomers.title': { es: 'Soy Nuevo', en: 'Connect' },
  'newcomers.subtitle': { es: 'Te damos la bienvenida a nuestra familia de fe. Estamos emocionados de que estés aquí.', en: 'We welcome you to our family of faith. We are excited that you are here.' },
  'newcomers.welcomeTitle': { es: '¡Bienvenido a Casa!', en: 'Welcome Home!' },
  'newcomers.welcomeText1': { es: 'Ya sea que estés visitando por primera vez o buscando una iglesia donde llamar hogar, estamos muy contentos de que estés aquí. En I.C.G.G., creemos que la iglesia es más que un edificio, es una familia.', en: 'Whether you\'re visiting for the first time or looking for a church to call home, we are so glad you are here. At I.C.G.G., we believe that church is more than a building—it\'s a family.' },
  'newcomers.welcomeText2': { es: 'Nuestra pasión es ayudarte a crecer en tu relación con Dios, conectarte con otros creyentes y descubrir el propósito que Dios tiene para tu vida.', en: 'Our passion is to help you grow in your relationship with God, connect with other believers, and discover the purpose God has for your life.' },
  'newcomers.connect': { es: 'Conectar', en: 'Connect' },
  'newcomers.connectDesc': { es: 'Únete a un grupo pequeño y construye relaciones auténticas', en: 'Join a small group and build authentic relationships' },
  'newcomers.serve': { es: 'Servir', en: 'Serve' },
  'newcomers.serveDesc': { es: 'Descubre tus dones y sirve en nuestros ministerios', en: 'Discover your gifts and serve in our ministries' },
  'newcomers.events': { es: 'Eventos', en: 'Events' },
  'newcomers.eventsDesc': { es: 'Mantente conectado con nuestras actividades especiales', en: 'Stay connected with our special activities' },
  'newcomers.serviceTimesDesc': { es: 'Ven y Vistenos, tu vida jamas sera igual', en: 'Come and Visit Us, your life will never be the same' },
  'newcomers.give': { es: 'Dar', en: 'Give' },
  'newcomers.giveDesc': { es: 'Apoya la misión de la iglesia con tus ofrendas', en: 'Support the church mission with your offerings' },
  'newcomers.whatToExpect': { es: '¿Qué Esperar en Tu Primera Visita?', en: 'What to Expect on Your First Visit?' },
  'newcomers.arrival': { es: 'Llegada', en: 'Arrival' },
  'newcomers.arrivalDesc': { es: 'Nuestro equipo de bienvenida te recibirá con una sonrisa. Llega 15 minutos antes para recibir una orientación y conocer las instalaciones.', en: 'Our welcome team will greet you with a smile. Arrive 15 minutes early for an orientation and tour of the facilities.' },
  'newcomers.service': { es: 'Servicio', en: 'Service' },
  'newcomers.serviceDesc': { es: 'Experimenta adoración viva, enseñanza bíblica práctica y una atmósfera donde puedes encontrarte con Dios. Los servicios duran aproximadamente 90 minutos.', en: 'Experience vibrant worship, practical biblical teaching, and an atmosphere where you can encounter God. Services last approximately 90 minutes.' },
  'newcomers.community': { es: 'Comunidad', en: 'Community' },
  'newcomers.communityDesc': { es: 'Después del servicio, te invitamos a quedarte para café y conocer a otros miembros de nuestra familia de fe.', en: 'After the service, we invite you to stay for coffee and meet other members of our faith family.' },
  'newcomers.planVisit': { es: 'Planifica Tu Visita', en: 'Plan Your Visit' },
  'newcomers.location': { es: 'Ubicación', en: 'Location' },
  'newcomers.serviceTimes': { es: 'Horarios de Servicio', en: 'Service Times' },
  'newcomers.sundayService': { es: 'Domingos: 10:00 AM', en: 'Sundays: 10:00 AM' },
  'newcomers.thursdayService': { es: 'Jueves: 7:30 PM', en: 'Thursdays: 7:30 PM' },
  'newcomers.dresscode': { es: 'Código de Vestimenta', en: 'Dress Code' },
  'newcomers.dresscodeDesc': { es: 'Ven como te sientas cómodo. Lo importante es tu corazón, no tu ropa.', en: 'Come as you feel comfortable. What matters is your heart, not your clothes.' },
  'newcomers.contactUs': { es: 'Contáctanos', en: 'Contact Us' },
  'newcomers.nextSteps': { es: 'Próximos Pasos', en: 'Next Steps' },
  'newcomers.nextStepsDesc': { es: '¿Listo para dar el siguiente paso? Descubre más sobre nuestra iglesia, nuestras creencias y cómo puedes ser parte de esta familia.', en: 'Ready to take the next step? Discover more about our church, our beliefs, and how you can be part of this family.' },
  'newcomers.learnMore': { es: 'Conoce Más', en: 'Learn More' },
  'newcomers.viewServices': { es: 'Ver Servicios', en: 'View Services' },

  // Prayer Section
  'prayer.title': { es: 'Peticiones de Oración', en: 'Prayer Requests' },
  'prayer.subtitle': { es: '"Orad sin cesar. Dad gracias en todo, porque esta es la voluntad de Dios para con vosotros en Cristo Jesús." - 1 Tesalonicenses 5:16-18', en: '"Pray without ceasing. In everything give thanks; for this is the will of God in Christ Jesus for you." - 1 Thessalonians 5:16-18' },
  'prayer.formTitle': { es: 'Comparte tu Petición de Oración', en: 'Share Your Prayer Request' },
  'prayer.formDescription': { es: 'Nos encantaría orar contigo y por ti. Comparte tus necesidades con nuestra familia de fe.', en: 'We would love to pray with you and for you. Share your needs with our family of faith.' },
  'prayer.fullName': { es: 'Nombre Completo', en: 'Full Name' },
  'prayer.fullNamePlaceholder': { es: 'Tu nombre completo', en: 'Your full name' },
  'prayer.email': { es: 'Correo Electrónico', en: 'Email' },
  'prayer.emailPlaceholder': { es: 'tu@email.com', en: 'your@email.com' },
  'prayer.phone': { es: 'Teléfono', en: 'Phone' },
  'prayer.phonePlaceholder': { es: '(407) 555-1234', en: '(407) 555-1234' },
  'prayer.message': { es: 'Tu Petición de Oración', en: 'Your Prayer Request' },
  'prayer.messagePlaceholder': { es: 'Comparte tu petición de oración...', en: 'Share your prayer request...' },
  'prayer.confidentiality': { es: 'Confidencialidad:', en: 'Confidentiality:' },
  'prayer.confidentialityMessage': { es: 'Todas las peticiones son tratadas con respeto y confidencialidad.', en: 'All requests are treated with respect and confidentiality.' },
  'prayer.submit': { es: 'Enviar Petición', en: 'Submit Request' },
  'prayer.sending': { es: 'Enviando...', en: 'Sending...' },
  'prayer.thankYou': { es: '¡Gracias por compartir!', en: 'Thank you for sharing!' },
  'prayer.thankYouMessage': { es: 'Hemos recibido tu petición de oración. Estaremos orando por ti.', en: 'We have received your prayer request. We will be praying for you.' }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [isSpanish, setIsSpanish] = useState(true);

  const toggleLanguage = () => {
    setIsSpanish(!isSpanish);
  };

  const t = (key: string): string => {
    const translation = translations[key as keyof typeof translations];
    if (!translation) {
      console.warn(`Translation missing for key: ${key}`);
      return key;
    }
    return isSpanish ? translation.es : translation.en;
  };

  return (
    <LanguageContext.Provider value={{ isSpanish, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};